name: Check PR

on:
  pull_request:

jobs:
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Node Version
        id: node-version
        run: echo "node-version=$(cat .node-version)" >> $GITHUB_OUTPUT

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}

      - name: Install Dependencies
        run: npm ci

      - run: npm test
