name: Publish Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Node Version
        id: node-version
        run: echo "node-version=$(cat .node-version)" >> $GITHUB_OUTPUT

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack
        id: pack
        run: |
          filename="$(npm pack --dry-run --json | jq -r '.[0].filename')"
          npm pack
          echo "filename=$filename" >> $GITHUB_OUTPUT

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get Semver
        id: semver
        run: echo "version=$(echo '${{ github.ref_name }}'' | tr 'v' ' ' | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          body: |
            [View on NPM](https://www.npmjs.com/package/eslint-plugin-preact-signals/v/${{ steps.semver.outputs.version }})
          files: |
            ${{ steps.pack.outputs.filename }}
